# Generated by Django 6.1.1 on 2026-10-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва кафедри')),
                ('head', models.CharField(max_length=255, verbose_name='Завідувач кафедри')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедри',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Факультет природничих наук НаУКМА', max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис факультету')),
                ('contacts', models.TextField(verbose_name='Контакти')),
            ],
            options={
                'verbose_name': 'Текст головної сторінки',
                'verbose_name_plural': 'Текст головної сторінки',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва спеціальності')),
                ('code', models.CharField(max_length=20, verbose_name='Код спеціальності')),
                ('description', models.TextField(verbose_name='Опис')),
                ('coordinator_name', models.CharField(max_length=255, verbose_name="Ім'я координатора набору")),
                ('coordinator_contact', models.CharField(max_length=255, verbose_name='Контакт координатора набору')),
                ('disciplines', models.TextField(verbose_name='Список дисциплін (по роках/триместрах)')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='core.department', verbose_name='Випускова кафедра')),
            ],
            options={
                'verbose_name': 'Спеціальність',
                'verbose_name_plural': 'Спеціальності',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я (ПІБ)")),
                ('position', models.CharField(max_length=255, verbose_name='Посада')),
                ('degree', models.CharField(max_length=255, verbose_name='Науковий ступінь / Вчене звання')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
            },
        ),
    ]
